apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
data:
  CART_ENDPOINT: "CART:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  #these labels are replicaset labels, these labels are used to identify the pods which are created by this deployment
  labels:
    project: roboshop
    component: shipping
    tier: backend 

spec:
  replicas: 1

  selector:
    matchLabels:
      project: roboshop
      component: shipping
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: shipping
        tier: backend

    spec:
      containers:
      - name: shipping
        image: prem1440docker/shipping:1.4.0
        imagePullPolicy: Always #safe to pull evertime,there may be images with same version rebuilt and pushed
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
           # httpGet:
           # path: /health
           # port: 8080
          tcpSocket:
            port: 8080 
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15 
        startupProbe:
           httpGet:
            path: /health
            port: 8080
           initialDelaySeconds: 10
           periodSeconds: 5 

        livenessProbe:
                httpGet:
                    path: /health
                    port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                failureThreshold: 2            
                    
        envFrom:
        - configMapRef:
            name: shipping
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
  labels:
    project: roboshop
    component: shipping
    tier: backend
spec:
  selector:
  #labels are used to select the pods for which this service will be created
    project: roboshop
    component: shipping
    tier: backend
  ports:
  - protocol: TCP 
    port: 27017 #port on which the service will be exposed
    targetPort: 27017 #container port to which the traffic will be forwarded