apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
data:
  MONGO: "true"
  MONGO_URL: "mongodb://mongodb:27017/catalogue" 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  namespace: roboshop
  #these labels are replicaset labels, these labels are used to identify the pods which are created by this deployment
  labels:
    project: roboshop
    component: catalogue
    tier: backend 

spec:
  replicas: 1

  selector:
    matchLabels:
      project: roboshop
      component: catalogue
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: catalogue
        tier: backend

    spec:
      containers:
      - name: catalogue
        image: joindevops/catalogue:1.0.0
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
           # httpGet:
           # path: /health
           # port: 8080
          tcpSocket:
            port: 8080 
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15 

        livenessProbe:
                httpGet:
                    httpGet:
                    path: /health
                    port: 8080
                    initialDelaySeconds: 30
                    periodSeconds: 10
                    failureThreshold: 2
                    
          
        envFrom:
        - configMapRef:
            name: catalogue
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  namespace: roboshop
  labels:
    project: roboshop
    component: catalogue
    tier: backend
spec:
  selector:
  #labels are used to select the pods for which this service will be created
    project: roboshop
    component: catalogue
    tier: backend
  ports:
  - protocol: TCP 
    port: 27017 #port on which the service will be exposed
    targetPort: 27017 #container port to which the traffic will be forwarded