apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
data:
  
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
  MONGO: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  #these labels are replicaset labels, these labels are used to identify the pods which are created by this deployment
  labels:
    project: roboshop
    component: user
    tier: backend 

spec:
  replicas: 1

  selector:
    matchLabels:
      project: roboshop
      component: user
      tier: backend

  template:
    metadata:
      labels:
        project: roboshop
        component: user
        tier: backend

    spec:
      containers:
      - name: user
        image: prem1440docker/user:1.4.0
        imagePullPolicy: Always #safe to pull evertime,there may be images with same version rebuilt and pushed
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        readinessProbe:
           # httpGet:
           # path: /health
           # port: 8080
          tcpSocket:
            port: 8080 
          failureThreshold: 2
          periodSeconds: 10
          initialDelaySeconds: 15 

        livenessProbe:
                httpGet:
                    path: /health
                    port: 8080
                initialDelaySeconds: 30
                periodSeconds: 10
                failureThreshold: 2            
                    
        envFrom:
        - configMapRef:
            name: user
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
  labels:
    project: roboshop
    component: user
    tier: backend
spec:
  selector:
  #labels are used to select the pods for which this service will be created
    project: roboshop
    component: user
    tier: backend
  ports:
  - protocol: TCP 
    port: 8080 #port on which the service will be exposed
    targetPort: 8080 #container port to which the traffic will be forwarded