apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: roboshop
  #these labels are replicaset labels, these labels are used to identify the pods which are created by this deployment
  labels:
    project: roboshop
    component: redis
    tier: db 

spec:
  replicas: 1

  selector:
    matchLabels:
      project: roboshop
      component: redis
      tier: db

  template:
    metadata:
      labels:
        project: roboshop
        component: redis
        tier: db

    spec:
      containers:
      - name: redis
        image: redis:7.0
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels:
    project: roboshop
    component: redis
    tier: db
spec:
  selector:
  #labels are used to select the pods for which this service will be created
    project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP 
    port: 6379 #port on which the service will be exposed
    targetPort: 6379 #container port to which the traffic will be forwarded